export const FETCHING_PROFILE_INFORMATION = 'FETCHING_PROFILE_INFORMATION'
export const UPDATE_PROFILE_INFORMATION = 'UPDATE_PROFILE_INFORMATION'
export const ERROR_PROFILE_INFORMATION = 'ERROR_PROFILE_INFORMATION'
